source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'7.0'

target 'FPDemo4iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #Pods for FPDemo
    pod 'BlocksKit'
    pod 'ReactiveCocoa'
  #end
end



